name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "drivenops_test"
          envkey_DATABASE_URL: "postgres://postgres:postgres@postgres_drivenops_db:5432/drivenops_test"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_drivenops_app npm run test
      - name: Build
        run: npm i && npm run build
